using System.Text;
using System.Text.Json;
using Wendmem.Serialization;

namespace Wendmem.Cli.Commands;

internal static class GraphHtmlRenderer
{
    public static string Render(GraphData data)
    {
        var nodesJson = JsonSerializer.Serialize(data.Nodes, WendmemJsonContext.Default.ListGraphNode);
        var linksJson = JsonSerializer.Serialize(data.Links, WendmemJsonContext.Default.ListGraphLink);

        var sb = new StringBuilder(80 * 1024);

        // ── HEAD ──────────────────────────────────────────────
        sb.Append("""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

""");
        sb.AppendLine("<!-- generated by wendmem graph");
        sb.AppendLine($"     wing: {data.Wing}");
        sb.AppendLine($"     nodes: {data.Nodes.Count}  links: {data.Links.Count}");
        sb.AppendLine($"     at: {data.GeneratedAt:u} -->");
        sb.Append("""
<title>wendmem — knowledge palace</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js"></script>

""");

        // ── CSS (verbatim from template) ──────────────────────
        sb.Append(CssBlock);

        sb.Append("""
</head>
<body>

""");

        // ── HTML BODY (verbatim from template) ────────────────
        sb.Append(HtmlBody);

        // ── SCRIPT ────────────────────────────────────────────
        sb.Append(JsHeader);

        sb.AppendLine();
        sb.Append("const nodes = ");
        sb.Append(nodesJson);
        sb.AppendLine(";");

        sb.AppendLine();
        sb.Append(JsLabelBuilder);

        sb.AppendLine();
        sb.Append("const links = ");
        sb.Append(linksJson);
        sb.AppendLine(";");

        sb.AppendLine();
        sb.Append(JsMain);

        sb.Append("""
</script>
</body>
</html>
""");

        return sb.ToString();
    }

    private const string CssBlock = """
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500&family=Crimson+Pro:ital,wght@0,300;0,400;1,300&display=swap');

  :root {
    --bg:        #0d0f14;
    --surface:   #13161e;
    --border:    #1e2433;
    --muted:     #2a3045;
    --text:      #c8cdd8;
    --dim:       #5a6380;
    --accent:    #7c9fd4;
    --gold:      #c9a84c;
    --rose:      #c47c7c;
    --sage:      #6b9e7e;
    --lavender:  #9b85c4;
    --teal:      #5d9ea8;
    --orange:    #c47c44;

    /* node types */
    --col-wing:    #7c9fd4;
    --col-wiki:    #6b9e7e;
    --col-triple:  #c9a84c;
    --col-drawer:  #9b85c4;
    --col-episode: #c47c7c;
    --col-skill:   #5d9ea8;
  }

  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    background: var(--bg);
    color: var(--text);
    font-family: 'JetBrains Mono', monospace;
    font-size: 12px;
    overflow: hidden;
    height: 100vh;
    width: 100vw;
  }

  /* ── chrome ─────────────────────────────────────────── */
  #header {
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 48px;
    background: var(--surface);
    border-bottom: 1px solid var(--border);
    display: flex;
    align-items: center;
    padding: 0 20px;
    gap: 16px;
    z-index: 100;
  }

  .logo {
    font-family: 'Crimson Pro', serif;
    font-size: 17px;
    font-style: italic;
    font-weight: 300;
    color: var(--accent);
    letter-spacing: 0.04em;
    flex-shrink: 0;
  }

  .logo span {
    color: var(--dim);
    font-style: normal;
    font-size: 11px;
    margin-left: 6px;
    letter-spacing: 0.12em;
    text-transform: uppercase;
  }

  .divider { width: 1px; height: 20px; background: var(--border); }

  #search {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 4px;
    color: var(--text);
    font-family: 'JetBrains Mono', monospace;
    font-size: 11px;
    padding: 5px 10px;
    width: 180px;
    outline: none;
    transition: border-color 0.15s;
  }
  #search:focus { border-color: var(--accent); }
  #search::placeholder { color: var(--dim); }

  .filter-row {
    display: flex;
    gap: 6px;
    align-items: center;
    flex-wrap: nowrap;
  }

  .filter-btn {
    background: none;
    border: 1px solid var(--muted);
    border-radius: 3px;
    color: var(--dim);
    font-family: 'JetBrains Mono', monospace;
    font-size: 10px;
    padding: 4px 8px;
    cursor: pointer;
    transition: all 0.15s;
    display: flex;
    align-items: center;
    gap: 5px;
    white-space: nowrap;
  }
  .filter-btn.active { border-color: currentColor; color: var(--text); }
  .filter-btn:hover { border-color: var(--accent); color: var(--accent); }

  .filter-btn .dot {
    width: 7px; height: 7px;
    border-radius: 50%;
    flex-shrink: 0;
  }

  .spacer { flex: 1; }

  #stats-bar {
    font-size: 10px;
    color: var(--dim);
    display: flex;
    gap: 12px;
    white-space: nowrap;
  }
  #stats-bar span { color: var(--text); }

  /* ── graph canvas ────────────────────────────────────── */
  #graph {
    position: absolute;
    top: 48px; left: 0; right: 280px; bottom: 0;
  }

  svg {
    width: 100%;
    height: 100%;
  }

  /* edges */
  .link {
    stroke: var(--muted);
    stroke-opacity: 0.6;
    fill: none;
    transition: stroke-opacity 0.2s, stroke 0.2s;
  }
  .link.wing-link    { stroke: var(--col-wing);    stroke-opacity: 0.25; }
  .link.wiki-link    { stroke: var(--col-wiki);    stroke-opacity: 0.25; }
  .link.triple-link  { stroke: var(--col-triple);  stroke-opacity: 0.25; }
  .link.episode-link { stroke: var(--col-episode); stroke-opacity: 0.25; }
  .link.skill-link   { stroke: var(--col-skill);   stroke-opacity: 0.25; }
  .link.highlighted  { stroke-opacity: 0.9 !important; stroke-width: 2; }
  .link.faded        { stroke-opacity: 0.04; }

  /* nodes */
  .node circle {
    stroke-width: 1.5;
    cursor: pointer;
    transition: r 0.15s, filter 0.15s;
  }
  .node:hover circle { filter: brightness(1.35); }
  .node.selected circle { stroke-width: 3; filter: brightness(1.5); }
  .node.faded circle { opacity: 0.12; }
  .node.faded text  { opacity: 0.05; }

  .node text {
    font-family: 'JetBrains Mono', monospace;
    font-size: 9.5px;
    fill: var(--text);
    pointer-events: none;
    dominant-baseline: central;
  }

  .node.wing-node text   { font-size: 11px; fill: var(--col-wing); }
  .node.selected text    { font-weight: 500; }

  /* ── sidebar ─────────────────────────────────────────── */
  #sidebar {
    position: absolute;
    top: 48px; right: 0; bottom: 0;
    width: 280px;
    background: var(--surface);
    border-left: 1px solid var(--border);
    overflow-y: auto;
    padding: 0;
    z-index: 50;
  }

  .sidebar-section {
    border-bottom: 1px solid var(--border);
    padding: 14px 16px;
  }

  .sidebar-section h3 {
    font-size: 9px;
    letter-spacing: 0.15em;
    text-transform: uppercase;
    color: var(--dim);
    margin-bottom: 8px;
  }

  #node-detail { display: none; }
  #node-detail.visible { display: block; }

  .detail-type {
    display: inline-block;
    font-size: 9px;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    padding: 2px 8px;
    border-radius: 2px;
    margin-bottom: 8px;
  }

  .detail-title {
    font-family: 'Crimson Pro', serif;
    font-size: 18px;
    font-weight: 300;
    color: var(--text);
    line-height: 1.3;
    margin-bottom: 6px;
    word-break: break-word;
  }

  .detail-meta {
    font-size: 10px;
    color: var(--dim);
    margin-bottom: 4px;
    display: flex;
    align-items: flex-start;
    gap: 6px;
  }
  .detail-meta .key { color: var(--accent); min-width: 64px; flex-shrink: 0; }

  .detail-content {
    font-size: 11px;
    color: var(--dim);
    line-height: 1.6;
    margin-top: 8px;
    font-family: 'Crimson Pro', serif;
    font-weight: 300;
    font-style: italic;
  }

  .connections-list {
    list-style: none;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .connections-list li {
    font-size: 10px;
    color: var(--dim);
    padding: 4px 8px;
    border-radius: 3px;
    background: var(--bg);
    cursor: pointer;
    display: flex;
    align-items: center;
    gap: 6px;
    transition: color 0.15s;
  }
  .connections-list li:hover { color: var(--text); }
  .connections-list li .dot { width: 6px; height: 6px; border-radius: 50%; flex-shrink: 0; }
  .connections-list li .lbl { color: var(--dim); font-size: 9px; }

  .predicate-badge {
    font-size: 8.5px;
    color: var(--gold);
    background: rgba(201,168,76,0.1);
    border: 1px solid rgba(201,168,76,0.2);
    border-radius: 2px;
    padding: 1px 5px;
  }

  /* legend */
  .legend-item {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 10px;
    color: var(--dim);
    padding: 3px 0;
    cursor: pointer;
    transition: color 0.15s;
  }
  .legend-item:hover { color: var(--text); }
  .legend-item .dot { width: 9px; height: 9px; border-radius: 50%; flex-shrink: 0; }
  .legend-item .count { margin-left: auto; color: var(--muted); }

  /* empty state */
  #empty-state {
    padding: 24px 16px;
    text-align: center;
  }
  #empty-state .icon {
    font-family: 'Crimson Pro', serif;
    font-size: 32px;
    font-style: italic;
    color: var(--muted);
    margin-bottom: 8px;
  }
  #empty-state p {
    font-size: 10px;
    color: var(--dim);
    line-height: 1.6;
  }

  /* scrollbar */
  #sidebar::-webkit-scrollbar { width: 4px; }
  #sidebar::-webkit-scrollbar-track { background: transparent; }
  #sidebar::-webkit-scrollbar-thumb { background: var(--muted); border-radius: 2px; }

  /* tooltip */
  #tooltip {
    position: absolute;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 4px;
    padding: 6px 10px;
    font-size: 10px;
    color: var(--text);
    pointer-events: none;
    display: none;
    z-index: 200;
    max-width: 200px;
    line-height: 1.4;
  }

  /* controls */
  #controls {
    position: absolute;
    bottom: 16px;
    left: 16px;
    display: flex;
    gap: 6px;
    z-index: 100;
  }
  .ctrl-btn {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 4px;
    color: var(--dim);
    font-family: 'JetBrains Mono', monospace;
    font-size: 13px;
    width: 30px; height: 30px;
    cursor: pointer;
    display: flex; align-items: center; justify-content: center;
    transition: all 0.15s;
  }
  .ctrl-btn:hover { border-color: var(--accent); color: var(--accent); }

  /* glow on wing nodes */
  @keyframes pulse-glow {
    0%, 100% { filter: drop-shadow(0 0 4px currentColor); }
    50%       { filter: drop-shadow(0 0 10px currentColor); }
  }
  .wing-node circle { animation: pulse-glow 3s ease-in-out infinite; }
</style>

""";

    private const string HtmlBody = """
<!-- header -->
<div id="header">
  <div class="logo">wendmem <span>palace</span></div>
  <div class="divider"></div>
  <input id="search" type="text" placeholder="search nodes…" autocomplete="off">
  <div class="divider"></div>
  <div class="filter-row" id="filters"></div>
  <div class="spacer"></div>
  <div id="stats-bar"></div>
</div>

<!-- graph -->
<div id="graph">
  <svg id="svg"></svg>
</div>

<!-- sidebar -->
<div id="sidebar">
  <div class="sidebar-section">
    <h3>legend</h3>
    <div id="legend"></div>
  </div>
  <div id="node-detail" class="sidebar-section">
    <!-- filled by JS -->
  </div>
  <div id="empty-state" class="sidebar-section">
    <div class="icon">∮</div>
    <p>Click any node to inspect it.<br>Drag to rearrange. Scroll to zoom.</p>
  </div>
</div>

<!-- tooltip -->
<div id="tooltip"></div>

<!-- controls -->
<div id="controls">
  <button class="ctrl-btn" id="zoom-in"  title="Zoom in">+</button>
  <button class="ctrl-btn" id="zoom-out" title="Zoom out">−</button>
  <button class="ctrl-btn" id="reset"    title="Reset view">⊙</button>
</div>

""";

    private const string JsHeader = """
<script>
const TYPES = {
  wing:    { label: 'Wing',      color: 'var(--col-wing)',    r: 18 },
  wiki:    { label: 'Wiki page', color: 'var(--col-wiki)',    r: 11 },
  triple:  { label: 'KG triple', color: 'var(--col-triple)',  r: 8  },
  drawer:  { label: 'Drawer',    color: 'var(--col-drawer)',  r: 6  },
  episode: { label: 'Episode',   color: 'var(--col-episode)', r: 9  },
  skill:   { label: 'Skill',     color: 'var(--col-skill)',   r: 9  },
};

""";

    private const string JsLabelBuilder = """
// Build label for display
nodes.forEach(n => {
  if (!n.label) {
    if (n.type === 'triple')  n.label = `${n.subject} ${n.predicate} ${n.object}`;
    if (n.type === 'episode') n.label = n.goal ? (n.goal.length > 38 ? n.goal.slice(0,38)+'…' : n.goal) : n.id;
    if (n.type === 'skill')   n.label = n.name;
  }
});

""";

    // The main JS logic block — verbatim from template lines 536-905
    // Using a raw string literal to preserve all JS exactly.
    // C# raw strings (""") don't need escaping for " or ${} in content.
    private const string JsMain = """
// ── D3 SETUP ──────────────────────────────────────────────────────────────────
const graphEl = document.getElementById('graph');
const svg = d3.select('#svg');
const tooltip = document.getElementById('tooltip');

let width  = graphEl.clientWidth;
let height = graphEl.clientHeight;

const g = svg.append('g').attr('class', 'graph-root');

// zoom
const zoom = d3.zoom()
  .scaleExtent([0.15, 4])
  .on('zoom', e => g.attr('transform', e.transform));
svg.call(zoom);

// simulation
const sim = d3.forceSimulation(nodes)
  .force('link',   d3.forceLink(links).id(d => d.id).distance(d => {
    if (d.source.type === 'wing' && d.target.type === 'wing') return 240;
    if (d.target.type === 'triple') return 110;
    if (d.target.type === 'drawer') return 80;
    return 140;
  }).strength(0.6))
  .force('charge', d3.forceManyBody().strength(d => {
    if (d.type === 'wing')   return -600;
    if (d.type === 'wiki')   return -220;
    if (d.type === 'triple') return -140;
    return -80;
  }))
  .force('collide', d3.forceCollide().radius(d => TYPES[d.type].r * 1.8))
  .force('center',  d3.forceCenter(width / 2, height / 2))
  .force('x', d3.forceX(width / 2).strength(0.04))
  .force('y', d3.forceY(height / 2).strength(0.04));

// edges
const linkEls = g.append('g').attr('class', 'links')
  .selectAll('line')
  .data(links)
  .join('line')
    .attr('class', d => `link ${d.type}-link`);

// node groups
const nodeEls = g.append('g').attr('class', 'nodes')
  .selectAll('.node')
  .data(nodes)
  .join('g')
    .attr('class', d => `node ${d.type}-node`)
    .call(d3.drag()
      .on('start', dragStart)
      .on('drag',  dragged)
      .on('end',   dragEnd))
    .on('click',      onNodeClick)
    .on('mouseenter', onNodeEnter)
    .on('mouseleave', onNodeLeave);

nodeEls.append('circle')
  .attr('r', d => TYPES[d.type].r)
  .attr('fill', d => TYPES[d.type].color + '22')
  .attr('stroke', d => TYPES[d.type].color);

nodeEls.append('text')
  .attr('x', d => TYPES[d.type].r + 5)
  .attr('y', 0)
  .text(d => {
    const maxLen = d.type === 'wing' ? 20 : (d.type === 'triple' ? 30 : 22);
    const lbl = d.label || '';
    return lbl.length > maxLen ? lbl.slice(0, maxLen) + '…' : lbl;
  })
  .attr('fill', d => TYPES[d.type].color + 'cc')
  .style('display', d => ['drawer','triple'].includes(d.type) ? 'none' : null);

sim.on('tick', () => {
  linkEls
    .attr('x1', d => d.source.x)
    .attr('y1', d => d.source.y)
    .attr('x2', d => d.target.x)
    .attr('y2', d => d.target.y);
  nodeEls.attr('transform', d => `translate(${d.x},${d.y})`);
});

// ── interactions ──────────────────────────────────────────────────────────────
let selectedNode = null;
let activeFilters = new Set(Object.keys(TYPES)); // all on by default

function getNeighbourIds(node) {
  const ids = new Set([node.id]);
  links.forEach(l => {
    const s = l.source.id || l.source;
    const t = l.target.id || l.target;
    if (s === node.id) ids.add(t);
    if (t === node.id) ids.add(s);
  });
  return ids;
}

function onNodeClick(e, d) {
  e.stopPropagation();
  if (selectedNode && selectedNode.id === d.id) {
    // deselect
    selectedNode = null;
    nodeEls.classed('selected faded', false);
    linkEls.classed('highlighted faded', false);
    showEmptyState();
    return;
  }
  selectedNode = d;
  const neighbours = getNeighbourIds(d);
  nodeEls
    .classed('selected', n => n.id === d.id)
    .classed('faded',    n => !neighbours.has(n.id));
  linkEls
    .classed('highlighted', l => (l.source.id||l.source)===d.id || (l.target.id||l.target)===d.id)
    .classed('faded',       l => (l.source.id||l.source)!==d.id && (l.target.id||l.target)!==d.id);
  showNodeDetail(d, neighbours);
}

svg.on('click', () => {
  if (selectedNode) {
    selectedNode = null;
    nodeEls.classed('selected faded', false);
    linkEls.classed('highlighted faded', false);
    showEmptyState();
  }
});

function onNodeEnter(e, d) {
  if (selectedNode) return;
  tooltip.style.display = 'block';
  tooltip.style.left = (e.offsetX + 14) + 'px';
  tooltip.style.top  = (e.offsetY - 6)  + 'px';
  let html = `<strong>${d.label || d.name || ''}</strong>`;
  if (d.type === 'triple') html = `<strong>${d.subject}</strong> <span style="color:var(--gold)">${d.predicate}</span> ${d.object}`;
  if (d.type === 'drawer') html += `<br><span style="color:var(--dim)">${d.source}</span>`;
  tooltip.innerHTML = html;
}

function onNodeLeave() {
  tooltip.style.display = 'none';
}

function dragStart(e, d) {
  if (!e.active) sim.alphaTarget(0.3).restart();
  d.fx = d.x; d.fy = d.y;
}
function dragged(e, d)  { d.fx = e.x; d.fy = e.y; }
function dragEnd(e, d)  {
  if (!e.active) sim.alphaTarget(0);
  d.fx = null; d.fy = null;
}

// ── sidebar ───────────────────────────────────────────────────────────────────
function showEmptyState() {
  document.getElementById('node-detail').classList.remove('visible');
  document.getElementById('empty-state').style.display = 'block';
}

function showNodeDetail(d, neighbours) {
  document.getElementById('empty-state').style.display = 'none';
  const det = document.getElementById('node-detail');
  det.classList.add('visible');

  const typeInfo = TYPES[d.type];
  const connectedNodes = nodes.filter(n => neighbours.has(n.id) && n.id !== d.id);

  let html = `
    <div class="detail-type" style="background:${typeInfo.color}22;color:${typeInfo.color};border:1px solid ${typeInfo.color}44">
      ${typeInfo.label}
    </div>
    <div class="detail-title">${getTitle(d)}</div>
  `;

  // type-specific meta
  if (d.type === 'wing') {
    const wikiCount    = nodes.filter(n => n.type === 'wiki'    && n.wing === d.label).length;
    const tripleCount  = nodes.filter(n => n.type === 'triple'  && n.wing === d.label).length;
    const episodeCount = nodes.filter(n => n.type === 'episode' && n.wing === d.label).length;
    html += `
      <div class="detail-meta"><span class="key">wiki</span>${wikiCount} pages</div>
      <div class="detail-meta"><span class="key">triples</span>${tripleCount} facts</div>
      <div class="detail-meta"><span class="key">episodes</span>${episodeCount} recorded</div>
    `;
    if (d.desc) html += `<div class="detail-content">${d.desc}</div>`;
  }
  else if (d.type === 'wiki') {
    html += `
      <div class="detail-meta"><span class="key">wing</span>${d.wing}</div>
      <div class="detail-meta"><span class="key">path</span>${d.label}</div>
    `;
    if (d.citations?.length) html += `<div class="detail-meta"><span class="key">citations</span>${d.citations.length} drawers</div>`;
    if (d.desc) html += `<div class="detail-content">${d.desc}</div>`;
  }
  else if (d.type === 'triple') {
    html += `
      <div class="detail-meta"><span class="key">subject</span>${d.subject}</div>
      <div class="detail-meta"><span class="key">predicate</span><span class="predicate-badge">${d.predicate}</span></div>
      <div class="detail-meta"><span class="key">object</span>${d.object}</div>
      <div class="detail-meta"><span class="key">valid_from</span>${d.valid_from || d.validFrom}</div>
    `;
  }
  else if (d.type === 'drawer') {
    html += `
      <div class="detail-meta"><span class="key">id</span>${d.label}</div>
      <div class="detail-meta"><span class="key">wing</span>${d.wing}</div>
      <div class="detail-meta"><span class="key">room</span>${d.room}</div>
      <div class="detail-meta"><span class="key">source</span>${d.source}</div>
    `;
    if (d.snippet) html += `<div class="detail-content">"${d.snippet}"</div>`;
  }
  else if (d.type === 'episode') {
    const outcomeColor = d.outcome === 'success' ? 'var(--sage)' : d.outcome === 'failure' ? 'var(--rose)' : 'var(--gold)';
    html += `
      <div class="detail-meta"><span class="key">outcome</span><span style="color:${outcomeColor}">${d.outcome}</span></div>
      <div class="detail-meta"><span class="key">wing</span>${d.wing}</div>
    `;
    if (d.nextTime) html += `<div class="detail-content">${d.nextTime}</div>`;
  }
  else if (d.type === 'skill') {
    const pct = Math.round(d.successRate * 100);
    html += `
      <div class="detail-meta"><span class="key">path</span>${d.path || ''}</div>
      <div class="detail-meta"><span class="key">success</span><span style="color:var(--sage)">${pct}%</span></div>
      <div class="detail-meta"><span class="key">wing</span>${d.wing}</div>
    `;
    if (d.desc) html += `<div class="detail-content">${d.desc}</div>`;
  }

  // connections
  if (connectedNodes.length) {
    html += `<h3 style="font-size:9px;letter-spacing:.15em;text-transform:uppercase;color:var(--dim);margin-top:14px;margin-bottom:6px">${connectedNodes.length} connections</h3>
    <ul class="connections-list">`;
    connectedNodes.slice(0,10).forEach(n => {
      const col = TYPES[n.type].color;
      const lbl = (n.label || n.name || '').slice(0, 32);
      html += `<li onclick="selectNodeById('${n.id}')"><div class="dot" style="background:${col}"></div>${lbl}<span class="lbl" style="margin-left:auto">${n.type}</span></li>`;
    });
    if (connectedNodes.length > 10) html += `<li style="color:var(--muted);cursor:default">+${connectedNodes.length-10} more</li>`;
    html += '</ul>';
  }

  det.innerHTML = html;
}

function getTitle(d) {
  if (d.type === 'wing')    return d.label;
  if (d.type === 'wiki')    return d.title || d.label;
  if (d.type === 'triple')  return `${d.subject} → ${d.object}`;
  if (d.type === 'drawer')  return d.label;
  if (d.type === 'episode') return d.goal || d.label;
  if (d.type === 'skill')   return d.name || d.label;
  return d.label || d.id;
}

window.selectNodeById = function(id) {
  const d = nodes.find(n => n.id === id);
  if (!d) return;
  const neighbours = getNeighbourIds(d);
  selectedNode = d;
  nodeEls
    .classed('selected', n => n.id === d.id)
    .classed('faded',    n => !neighbours.has(n.id));
  linkEls
    .classed('highlighted', l => (l.source.id||l.source)===d.id || (l.target.id||l.target)===d.id)
    .classed('faded',       l => (l.source.id||l.source)!==d.id && (l.target.id||l.target)!==d.id);
  showNodeDetail(d, neighbours);
  // pan to node
  svg.transition().duration(400).call(
    zoom.transform,
    d3.zoomIdentity
      .translate(width/2, height/2)
      .scale(1.2)
      .translate(-d.x, -d.y)
  );
};

// ── legend + filters ──────────────────────────────────────────────────────────
const legendEl = document.getElementById('legend');
const filtersEl = document.getElementById('filters');

Object.entries(TYPES).forEach(([key, info]) => {
  const count = nodes.filter(n => n.type === key).length;

  // legend
  const li = document.createElement('div');
  li.className = 'legend-item';
  li.innerHTML = `<div class="dot" style="background:${info.color}"></div>${info.label}<span class="count">${count}</span>`;
  li.onclick = () => toggleFilter(key);
  legendEl.appendChild(li);

  // filter buttons in header
  const btn = document.createElement('button');
  btn.className = 'filter-btn active';
  btn.id = `filter-${key}`;
  btn.innerHTML = `<div class="dot" style="background:${info.color}"></div>${key}`;
  btn.onclick = () => toggleFilter(key);
  filtersEl.appendChild(btn);
});

function toggleFilter(key) {
  if (activeFilters.has(key)) {
    if (activeFilters.size === 1) return; // keep at least one
    activeFilters.delete(key);
  } else {
    activeFilters.add(key);
  }
  applyFilters();
}

function applyFilters() {
  Object.keys(TYPES).forEach(key => {
    const btn = document.getElementById(`filter-${key}`);
    if (btn) btn.classList.toggle('active', activeFilters.has(key));
  });
  nodeEls.style('display', d => activeFilters.has(d.type) ? null : 'none');
  linkEls.style('display', l => {
    const sn = nodes.find(n => n.id === (l.source.id||l.source));
    const tn = nodes.find(n => n.id === (l.target.id||l.target));
    return sn && tn && activeFilters.has(sn.type) && activeFilters.has(tn.type) ? null : 'none';
  });
  updateStats();
}

// ── search ────────────────────────────────────────────────────────────────────
document.getElementById('search').addEventListener('input', function() {
  const q = this.value.trim().toLowerCase();
  if (!q) {
    nodeEls.classed('faded', false);
    linkEls.classed('faded', false);
    return;
  }
  const matches = new Set(
    nodes
      .filter(n => JSON.stringify(n).toLowerCase().includes(q))
      .map(n => n.id)
  );
  nodeEls.classed('faded', d => !matches.has(d.id));
  linkEls.classed('faded', l => !matches.has(l.source.id||l.source) && !matches.has(l.target.id||l.target));
});

// ── stats ─────────────────────────────────────────────────────────────────────
function updateStats() {
  const visibleTypes = Object.keys(TYPES).filter(k => activeFilters.has(k));
  const visCount = nodes.filter(n => activeFilters.has(n.type)).length;
  const statsEl = document.getElementById('stats-bar');
  statsEl.innerHTML = `<span>${visCount}</span> nodes &nbsp;·&nbsp; <span>${links.length}</span> edges`;
}
updateStats();

// ── zoom controls ─────────────────────────────────────────────────────────────
document.getElementById('zoom-in').onclick  = () => svg.transition().call(zoom.scaleBy, 1.4);
document.getElementById('zoom-out').onclick = () => svg.transition().call(zoom.scaleBy, 0.7);
document.getElementById('reset').onclick    = () => {
  svg.transition().duration(600).call(
    zoom.transform,
    d3.zoomIdentity.translate(width/2, height/2).scale(0.9).translate(-width/2, -height/2)
  );
};

// ── resize ────────────────────────────────────────────────────────────────────
window.addEventListener('resize', () => {
  width  = graphEl.clientWidth;
  height = graphEl.clientHeight;
  sim.force('center', d3.forceCenter(width/2, height/2));
  sim.alpha(0.1).restart();
});

// initial fit after sim settles
sim.on('end', () => {
  svg.call(zoom.transform, d3.zoomIdentity.translate(width/2, height/2).scale(0.75).translate(-width/2, -height/2));
});
""";
}
