using System.Text.Json.Serialization;
using Wendmem.Cli.Commands;
using Wendmem.Eval;
using Wendmem.Experiences;
using Wendmem.Models;
using Wendmem.Tools;
using Wendmem.Wiki.Models;

namespace Wendmem.Serialization;

[JsonSourceGenerationOptions(
    WriteIndented = false,
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(ConfidenceThresholds))]
[JsonSerializable(typeof(ConfidenceConfig))]
[JsonSerializable(typeof(SuggestedAction))]
[JsonSerializable(typeof(McpError))]
[JsonSerializable(typeof(McpConfidence))]
[JsonSerializable(typeof(McpSignals))]
[JsonSerializable(typeof(McpMeta))]
[JsonSerializable(typeof(GetDrawerDto))]
[JsonSerializable(typeof(McpResponse<AddMemoryResult>))]
[JsonSerializable(typeof(McpResponse<DeleteMemoryResult>))]
[JsonSerializable(typeof(McpResponse<List<SearchMemoriesHit>>))]
[JsonSerializable(typeof(McpResponse<GetDrawerDto>))]
[JsonSerializable(typeof(McpResponse<IReadOnlyList<GrepExactResult>>))]
[JsonSerializable(typeof(McpResponse<AddTripleResult>))]
[JsonSerializable(typeof(McpResponse<InvalidateResult>))]
[JsonSerializable(typeof(McpResponse<WakeUpResult>))]
[JsonSerializable(typeof(WakeUpResult))]
[JsonSerializable(typeof(AddMemoryResult))]
[JsonSerializable(typeof(DeleteMemoryResult))]
[JsonSerializable(typeof(List<WingRoomEntry>))]
[JsonSerializable(typeof(List<SearchHit>))]
[JsonSerializable(typeof(List<SearchMemoriesHit>))]
[JsonSerializable(typeof(PruneResult))]
[JsonSerializable(typeof(List<DrawerGrepHit>))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(SaveSessionStateResult))]
[JsonSerializable(typeof(AddEntityResult))]
[JsonSerializable(typeof(ConflictInfo))]
[JsonSerializable(typeof(AddTripleResult))]
[JsonSerializable(typeof(InvalidateResult))]
[JsonSerializable(typeof(List<QueryTripleEntry>))]
[JsonSerializable(typeof(KgStatsResult))]
[JsonSerializable(typeof(MineFileResult))]
[JsonSerializable(typeof(MineConvResult))]
[JsonSerializable(typeof(SweepReportResult))]
[JsonSerializable(typeof(AddTunnelResult))]
[JsonSerializable(typeof(List<TunnelEntry>))]
[JsonSerializable(typeof(List<TunnelPair>))]
[JsonSerializable(typeof(List<SearchTaskMemoryEntry>))]
[JsonSerializable(typeof(DistillResult))]
[JsonSerializable(typeof(RecordOutcomeResult))]
[JsonSerializable(typeof(PruneTaskResult))]
[JsonSerializable(typeof(ExportTaskMemoryResult))]
[JsonSerializable(typeof(ImportTaskMemoryResult))]
[JsonSerializable(typeof(RecordToolCallResult))]
[JsonSerializable(typeof(SummarizeToolResult))]
[JsonSerializable(typeof(ToolGuidelinesResult))]
[JsonSerializable(typeof(ToolStatisticsResult))]
[JsonSerializable(typeof(List<ToolCallEntry>))]
[JsonSerializable(typeof(WalEntry))]
[JsonSerializable(typeof(Trajectory))]
[JsonSerializable(typeof(List<Trajectory>))]
[JsonSerializable(typeof(TrajectoryMessage))]
[JsonSerializable(typeof(List<TrajectoryMessage>))]
[JsonSerializable(typeof(RawMemoryDto))]
[JsonSerializable(typeof(List<RawMemoryDto>))]
[JsonSerializable(typeof(ValidationVerdictDto))]
[JsonSerializable(typeof(CallVerdictDto))]
[JsonSerializable(typeof(List<EntityCandidate>))]
[JsonSerializable(typeof(ExportLine))]
[JsonSerializable(typeof(Dictionary<string, string?>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<GrepExactResult>))]
[JsonSerializable(typeof(IReadOnlyList<GrepExactResult>))]
[JsonSerializable(typeof(McpResponse<RecordEpisodeResult>))]
[JsonSerializable(typeof(McpResponse<List<EpisodeDto>>))]
[JsonSerializable(typeof(RecordEpisodeResult))]
[JsonSerializable(typeof(EpisodeDto))]
[JsonSerializable(typeof(List<EpisodeDto>))]
[JsonSerializable(typeof(McpResponse<FindSkillDto>))]
[JsonSerializable(typeof(McpResponse<List<FindSkillDto>>))]
[JsonSerializable(typeof(FindSkillDto))]
[JsonSerializable(typeof(List<FindSkillDto>))]
[JsonSerializable(typeof(KgEvalResult))]
[JsonSerializable(typeof(EvalQuestion))]
[JsonSerializable(typeof(List<EvalQuestion>))]
[JsonSerializable(typeof(SkillEdit))]
[JsonSerializable(typeof(List<SkillEdit>))]
[JsonSerializable(typeof(SkillOptResult))]
[JsonSerializable(typeof(GraphNode))]
[JsonSerializable(typeof(GraphLink))]
[JsonSerializable(typeof(GraphData))]
[JsonSerializable(typeof(List<GraphNode>))]
[JsonSerializable(typeof(List<GraphLink>))]
public sealed partial class WendmemJsonContext : JsonSerializerContext;
